// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbjcegmyihkzdsdryjue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiamNlZ215aWhremRzZHJ5anVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Njg3NjksImV4cCI6MjA2MjQ0NDc2OX0.Z83rV40seIxTd7LdWoo1ooWJivLa2k6mW3VEcIfJ2jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);